name: Dynawo omc

on: [push]

defaults:
  run:
    shell: bash
jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Pre-requisites
        run: brew install automake

      - name: Install
        run: |
          git clone https://github.com/dynawo/dynawo.git
          cd dynawo
          printenv
          export DYNAWO_HOME=$(pwd)
          export DYNAWO_SRC_OPENMODELICA=$DYNAWO_HOME/OpenModelica/Source
          export DYNAWO_INSTALL_OPENMODELICA=$DYNAWO_HOME/OpenModelica/Install
          export DYNAWO_LOCALE=en_GB
          export DYNAWO_NB_PROCESSORS_USED=4
          export DYNAWO_BUILD_TYPE=Release
          export DYNAWO_CXX11_ENABLED=YES
          export DYNAWO_COMPILER=CLANG
          ./util/envDynawo.sh build-omcDynawo
